name: publish

on: 
  push:
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/publish.yml'
      - '**.tf'

jobs:
  publish-furryhappiness-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: 'update version'
      id: update-version
      shell: bash
      run: |
        buildDateNumber=$(date '+%Y.%m.%d')
        buildId=$GITHUB_RUN_NUMBER
        buildNumber="$buildDateNumber.$buildId"
        echo "$buildNumber"
        echo "::set-output name=BUILD_NUMBER::$buildNumber"

    - name: Build App
      run: dotnet build --configuration release --verbosity normal /nologo /property:GenerateFullPaths=true
      working-directory: src/FurryHappiness

    - name: Build Db
      run: dotnet build --configuration release --verbosity normal /nologo /property:GenerateFullPaths=true
      working-directory: src/FurryHappiness.Database
  
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the FurryHappiness-db Docker image
      run: |
        docker build --tag ghcr.io/dah-dah-demos/furryhappiness-db:${{ steps.update-version.outputs.BUILD_NUMBER }}-dev --tag ghcr.io/dah-dah-demos/furryhappiness-db:dev -f .github/workflows/db/Dockerfile .
        docker push ghcr.io/dah-dah-demos/furryhappiness-db:${{ steps.update-version.outputs.BUILD_NUMBER }}-dev
        docker push ghcr.io/dah-dah-demos/furryhappiness-db:dev
